#!/bin/bash

set -e
echo "[+] Aplicando actualizaciones en Debian 12..."

apt-mark hold openssh-server
apt update -y
apt upgrade -y

echo "[✔] Actualizaciones realizadas correctamente..."

#apt autoremove -y

#apt clean

# Ensure permissions on /etc/ssh/sshd_config are configured.
chown root:root /etc/ssh/sshd_config
chmod og-rwx /etc/ssh/sshd_config
# Change SSH Port to :25.
sed -i 's/^#Port 22/Port 25/' /etc/ssh/sshd_config
sed -i 's/^Port 22/Port 25/' /etc/ssh/sshd_config
# Ensure SSH X11 forwarding is disabled.
sed -i 's/^#X11Forwarding yes/X11Forwarding no/' /etc/ssh/sshd_config
sed -i 's/^X11Forwarding yes/X11Forwarding no/' /etc/ssh/sshd_config
# Ensure SSH MaxAuthTries is set to 4 or less.
sed -i 's/^#MaxAuthTries 6/MaxAuthTries 4/' /etc/ssh/sshd_config
sed -i 's/^MaxAuthTries 6/MaxAuthTries 4/' /etc/ssh/sshd_config
# Ensure SSH root login is disabled.
sed -i 's/^#PermitRootLogin yes/PermitRootLogin no/' /etc/ssh/sshd_config
sed -i 's/^PermitRootLogin yes/PermitRootLogin no/' /etc/ssh/sshd_config
# Ensure SSH access is limited.

# Ensure SSH warning banner is configured.
sed -i 's|^#*Banner .*|Banner /etc/issue.net|' /etc/ssh/sshd_config
grep -q "^Banner /etc/issue.net" /etc/ssh/sshd_config || echo "Banner /etc/issue.net" >> /etc/ssh/sshd_config
# Ensure SSH AllowTcpForwarding is disabled.
sed -i 's/^#AllowTcpForwarding yes/AllowTcpForwarding no/' /etc/ssh/sshd_config
sed -i 's/^AllowTcpForwarding yes/AllowTcpForwarding no/' /etc/ssh/sshd_config
# Ensure SSH MaxStartups is configured.
sed -i 's/^#MaxStartups 10:30:100/maxstartups 9:29:99/' /etc/ssh/sshd_config
sed -i 's/^MaxStartups 10:30:100/maxstartups 9:29:99/' /etc/ssh/sshd_config
