#!/bin/bash

set -e
echo "[+] Aplicando actualizaciones en Debian 12..."

apt-mark hold openssh-server
apt update -y
apt upgrade -y

echo "[✔] Actualizaciones realizadas correctamente..."

#apt autoremove -y

#apt clean
